### ISSUE TITLE
LogSync is not sending logs to https://console.cloud.google.com/logs/

### ISSUE THREAD

**Issue by GorvGoyl** [googleapis/nodejs-logging#1180] opened 2021-11-08 14:31 UTC
#### Environment details

  - OS: Win 10
  - Node.js version: 14
  - npm version: 6.14
  - `@google-cloud/logging` version: 9.6.2

#### Steps to reproduce

From the docs:
> Serverless applications like Cloud Functions, Cloud Run, and App Engine are highly recommended to use the LogSync class as async logs may be dropped due to lack of CPU.

This is our implementation of google cloud logging with `LogSync` class

```js
import { Logging } from "@google-cloud/logging";
const creds = {
  private_key:
    '---',
  client_email: "---",
};

const logging = new Logging({
  projectId,
  credentials: creds,
});

const log = logging.logSync(logName);

  const metadata = {
    resource: { type: "global" },
    severity,
    textPayload,
    jsonPayload,
  };

  const CombinedEntry = log.entry(metadata);


  log.alert(CombinedEntry);

```
 
We're using this in next.js framework and deploying on Vercel (as [serverless functions](https://vercel.com/docs/concepts/functions/serverless-functions))

These logs are visible in the console (stdout) but aren't visible on Google cloud logging.

Do we need to configure `LogSync` to mention that it should also send logs to google cloud logging? It's not mentioned in the docs.
We also tried `logging.log` instead of `LogSync` but still logs aren't visible on cloud just on `stdout`.

**Comment by losalex** [comment] 2021-12-20 23:49
@GorvGoyl,
Thank you very much for logging this issue and really sorry for late response!
I just tried the following sample which I ran in my sample Cloud Function and I can confirm that I can see log message in Cloud Logging Explorer:

```js
    import { Logging } from "@google-cloud/logging";

    const syncLogger = new Logging();
    // Create a LogSync transport, defaulting to process.stdout transport
    const log = syncLogger.logSync("my-log");
    const meta = { severity: "info" };
    const entry = log.entry(meta, 'Your log message');
    log.write(entry);
```

Can you please try the sample above in your function and see if it works as expected?

**Comment by GorvGoyl** [comment] 2021-12-22 20:30
@losalex this issue is specifically for the [Next.js/Vercel serverless functions](https://vercel.com/docs/concepts/functions/serverless-functions).

**Comment by losalex** [comment] 2021-12-22 21:09
I see - thanks @GorvGoyl for clarifications!
Just to clarify, your function code is not running in Google Cloud but you still want to write all logs generated by the function to Google Cloud Logging, correct?

**Comment by GorvGoyl** [comment] 2021-12-22 21:22
yes correct.

**Comment by losalex** [comment] 2021-12-23 00:37
Thank you @GorvGoyl for prompt reply.
The `LogSync` solution mentioned in Google Cloud docs works by default with `process.stdout` transport which requires corresponding agent to run on the same node/vm - such agent redirects stdout to Google Cloud Logging. Unfortunately, I am not sure if we have such agent solution available for [Next.js/Vercel serverless functions](https://vercel.com/docs/concepts/functions/serverless-functions). There is some explanation about agents [here](https://cloud.google.com/logging/docs/agent/logging), but I am not familiar with Vercel and cannot recommend you any specifics on a way to make it work for your case. Thats said I believe you can try to use `Logging.log` in your code and see if any data loss happens.
I was able to run following code in my local project executed from VSCode and see logging record created in Cloud Logging (just replace the GOOGLE_APPLICATION_CREDENTIALS with a filename of credentials JSON file on your computer and STARTUP_PROJECT_ID with your project ID):

```ts
    const syncLogger = new Logging({
        projectId: process.env.STARTUP_PROJECT_ID,
        keyFile: process.env.GOOGLE_APPLICATION_CREDENTIALS,
      });
  
    // Create a LogSync transport, defaulting to `process.stdout`
    const log = syncLogger.log("my-log");
    const meta = { severity: "info" };
    const entry = log.entry(meta, 'Your log message');
    log.write(entry);   
```

**Comment by GorvGoyl** [comment] 2021-12-23 14:41
I reached out to Vercel sometime back and they said they don't have default integration with Google cloud logging. Not sure if anything can be done now.

![image](https://user-images.githubusercontent.com/7106086/147255376-2e82897a-1436-4675-9ebb-2213ed87c13e.png)

**Comment by losalex** [comment] 2021-12-23 17:33
Yes, unfortunately the only way to have logs uploaded to Google Cloud is to use `Logging.log` as I already mentioned before. Were you able to use the sample I shared and see logs appear in logs explorer?

**Comment by GorvGoyl** [comment] 2021-12-24 16:59
`Logging.log` works if I use the async/await but then I have to await all logs calls. If I don't use async/await then sometimes serverless function gets terminated before the logger gets time to send logs to the server. I think it's the fundamental issue with serverless functions unless there's a native `stdout` integration available.

**Comment by losalex** [comment] 2021-12-28 20:03
Correct - in this case only native integration with `stdout` would be helpful. I am closing this issue since apparently there is nothing we can do on library level - @GorvGoyl, if you think different please reactivate this work item.

**Closed by losalex** 2021-12-28 20:03 UTC
Labels: type: question, api: logging
