### ISSUE TITLE
Slow require times (between 2 to 3 seconds) of logging-bunyan when used with Firebase functions

### ISSUE THREAD

**Issue by stephenhandley** [googleapis/nodejs-logging#317] opened 2018-08-17 22:05 UTC
#### Environment details

  - OS:  Firebase functions
  - Node.js version: 6.11.5
  - npm version: yarn 1.9.4
  - `@google-cloud/logging-bunyan` version: 0.8.2

#### Steps to reproduce

I am seeing particularly long cold start times consistently with Firebase functions and so did some basic instrumentation about which requires were the most time consuming. I'm seeing the time needed to require `logging-bunyan` to be consistently between 2 and 3 seconds when deployed to Firebase, but when running in local emulator to be around 200ms. 

I've also seen some intermittent errors causing the function to crash due to `Error: 14 UNAVAILABLE: TCP Read failed`
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-412200264

Not sure if they're related but I'm wondering if there's some underlying connectivity issue causing these long require times on firebase.

**Comment by JustinBeckwith** [comment] 2018-11-09 18:45
Ok, so I did an analysis here.  119ms of 396ms total load time (or about 30%) is taken up by loading the `globby` npm module.  This isn't really needed, since we're doing a simple `walk` to find proto files in a recursive directory structure.  This is the first place to start. 

![image](https://user-images.githubusercontent.com/534619/48281799-937d4100-e40c-11e8-8adf-1e5665148b69.png)

I am tracking that here:
https://github.com/googleapis/gax-nodejs/issues/341

**Comment by gakuba** [comment] 2018-12-13 07:45
I am seeing the same issue. I think for now I will have to try Winston and see if the issue is resolved.

**Comment by JustinBeckwith** [comment] 2019-02-15 03:26
Good news!  We've cut this down ever further.  We're now down to about 250ms of time to load.  As we move towards a native http2 implementation in grpc in the next few months, it will get even better:
![image](https://user-images.githubusercontent.com/534619/52832551-db57d800-308d-11e9-8d0d-9754216baf1d.png)

One thing you want to be really careful about - how do you instantiate your logging objects?  Where you instantiate the client (inside of the function or outside) makes a VERY bug difference on how long it will take to first load. 

Given the fact that we're down pretty low on the require time, with a plan to improve more, I'm going to close this out for now.  If folks are still seeing something you want us to look into - please let me know!

**Closed by JustinBeckwith** 2019-02-15 03:26 UTC
Labels: status: blocked, type: feature request
