### ISSUE TITLE
Versions > 5 don't work with firebase cloud functions

### ISSUE THREAD

**Issue by AndrewMorsillo** [googleapis/nodejs-logging#523] opened 2019-06-27 21:35 UTC
- OS: Firebase cloud functions
  - Node.js version: 10
  - `@google-cloud/logging` version: > 5

#### Steps to reproduce

  1. `npm install --save @google-cloud/logging`
  2. `import { Logging } from "@google-cloud/logging"`
  3. `firebase deploy --only functions`

Results in:

```
✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/path/to/my/app/functions/node_modules/@grpc/grpc-js/build/src/index.js:45:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/my/app/functions/node_modules/@google-cloud/common-grpc/build/src/index.js:18:14)
    at Module._compile (module.js:652:30)
```

**Comment by JustinBeckwith** [comment] 2019-06-27 23:03
Yikes!  Apologies for the troubles.  Quick question - are you adding anything to the `engines` field of your `package.json`? Or is this just happening because of what we have in our `package.json`?

**Comment by AndrewMorsillo** [comment] 2019-06-27 23:29
With firebase cloud functions you need to set "engines" to "8" or "10". Here is my package.json

```
{
    "name": "functions",
    "scripts": {
        "build": "tsc",
        "serve": "npm run build && firebase serve --only functions",
        "shell": "npm run build && firebase functions:shell",
        "start": "npm run shell",
        "deploy": "firebase deploy --only functions",
        "logs": "firebase functions:log"
    },
    "engines": {
        "node": "10"
    },
    "main": "lib/index.js",
    "dependencies": {
        "@google-cloud/logging": "^4.5.2",
        "firebase-admin": "~7.0.0",
        "firebase-functions": "^2.3.0",
        "request-promise": "^4.2.4"
    },
    "devDependencies": {
        "@types/request-promise": "^4.1.44",
        "typescript": "^3.2.2"
    },
    "private": true
}

```

I bumped @google-cloud/logging version to 4.5.2 to work around this for now. Unfortunately however logs aren't being written to stackdriver when I follow the example here: https://firebase.google.com/docs/functions/writing-and-viewing-logs I'm not sure if that is a result of using an older version of this library or if it is a document/firebase issue.

**Comment by jasonberryman** [comment] 2019-07-04 11:49
I'm having exactly the same issue when adding `@google-cloud/vision@1.1.3` to my project.  As soon as I add the following lines to my `index.js` file, I get the error `Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0`.  If I comment them, it install fine, but then I can't use the Vision API :(

```
const Vision = require('@google-cloud/vision');
const vision = new Vision.ImageAnnotationClient();
```

**Comment by jasonberryman** [comment] 2019-07-04 17:17
I have found a workaround for my issue with nodejs-vision which may resolve your issue deploying nodejs-logger to Cloud Functions for Firebase.  Instead of requiring the module at the global scope, require it inside a function.

#### index.js

```
// Don't put it here
// const logging = require('@google-cloud-logging');

exports.testLogging = functions.firestore
  .document('myCollection/{myDocId}').onCreate(async (snap, context) => {

  // Put it here
  const logging = require('@google-cloud-logging');

 // ...The rest of your code

});
```

**Comment by bcoe** [comment] 2019-07-08 21:49
@AndrewMorsillo what version of Node.js are you running on your local machine? I believe things will work as expected if you run Node@v10.15.3 locally.

**Comment by Elyx0** [comment] 2019-09-28 08:22
@jasonberryman Did you mean `@google-cloud/logging` ?

**Comment by bcoe** [comment] 2020-01-02 23:26
@AndrewMorsillo could I bother you to try running with the latest version of `@google-cloud/logging`, there have been quite a few updates to the library in recent months.

**Comment by bcoe** [comment] 2020-01-08 00:12
:wave: I am no longer able to reproduce this issue locally:

```
=== Deploying to 'redacted'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
✔  scheduler: all necessary APIs are enabled

✔  Deploy complete!
```

Closing for now, please let me know if folks are continuing to bump into any issue.

**Closed by bcoe** 2020-01-08 00:12 UTC
Labels: :rotating_light:, needs more info, priority: p2, type: bug
