### ISSUE TITLE
#98 Error: 3 INVALID_ARGUMENT: Log entry with size 6.23M exceeds maximum size of 256.0K

### ISSUE THREAD

**Issue by florent1933** [googleapis/nodejs-logging#520] opened 2019-06-18 06:24 UTC
#### Environment details

  - OS: Ubuntu Xenial
  - Node.js version: v8.11.2
  - `@google-cloud/logging-bunyan` version: 0.9.5

#### Steps to reproduce

  1. Create a big object bigger than 256ko
  2. logger.info(object, message);

It throws an error when it's happening and sometimes stop my node process

**Comment by ofrobots** [comment] 2019-06-18 23:56
@florent1933 can you provide a stack trace from the time of the error?

**Comment by florent1933** [comment] 2019-06-19 09:36
I don't have more than that.

I create a wrapper around the logger function to only send small objects but it doesn't work. I supposed the library combine logs and send it after.

**Comment by Tarty** [comment] 2019-07-12 08:32
Hello,

I am also currently affected by this issue using `@google-cloud/logging`. It's a bit annoying as the StackDriver documentation specify it is possible to batch logs up to 5MB.

It looks like the issue is not coming for `@google-cloud/logging` but from `@grpc/grpc-js` that is used under the hood.

Here is an example of the stack trace I'm getting:
```
message:  "Error: Log entry with size 344.6K exceeds maximum size of 256.0K
    at Http2CallStream.call.on (/srv/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"   
  name:  "Error"   
  value:  "{ Error: Log entry with size 344.6K exceeds maximum size of 256.0K
    at Http2CallStream.call.on (/srv/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) code: 3, details: 'Log entry with size 344.6K exceeds maximum size of 256.0K', metadata: Metadata { options: undefined, internalRepr: Map {} }, note: 'Exception occurred in retry method that was not classified as transient' }"   
```

**Comment by bcoe** [comment] 2019-07-15 21:33
CC: @alexander-fenster this is an odd one :point_up:

**Comment by alexander-fenster** [comment] 2019-07-15 22:11
This is not coming from grpc-js, but from the logging server. [This page](https://cloud.google.com/logging/quotas) says that, regardless of the batch size limit, the size of each entry cannot exceed 256K. This looks like the stackdriver API limitation, not a client library issue.

I'll close this for now, feel free to reopen if you have any questions! Thanks :)

**Closed by alexander-fenster** 2019-07-15 22:11 UTC
Labels: priority: p2, type: bug

**Comment by nandanraj56** [comment] 2021-05-03 12:04
Came across same issue.
Truncate your objects to 256 kb before sending
This is the only way

**Comment by mike-luabase** [comment] 2022-06-11 10:22
> Truncate your objects to 256 kb before sending

how did you do this? we're sending a JSON, so you can't really truncate it (will invalidate the JSON)

**Comment by TheGAFF** [comment] 2022-10-10 13:55
We have had this issue. In the context of GCP Cloud Run, it will actually crash containers and return `503 Service Unavailable` methods to subsequent requests to that container until a new container is started up by Cloud Run.

In our case, someone was logging an entire Axios error object and I suppose the GCP logger did not like all the nuances of that. Anyway, hope that helps someone debug the issue further.

**Comment by andreisaikouski** [comment] 2023-02-02 03:19
Has anyone determined a clear resolution?
Running into this issue as well. It is completely not clear where or which log makes it fail (see stack trace below).
But is there a clear way on _**how**_ to truncate json logs?

```
Feb 1 02:11:02 PM  Error: 3 INVALID_ARGUMENT: Log entry with size 2.38M exceeds maximum size of 256.0K
Feb 1 02:11:02 PM      at Object.callErrorFromStatus (/opt/render/project/src/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
Feb 1 02:11:02 PM      at Object.onReceiveStatus (/opt/render/project/src/node_modules/@grpc/grpc-js/build/src/client.js:195:52)
Feb 1 02:11:02 PM      at Object.onReceiveStatus (/opt/render/project/src/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
Feb 1 02:11:02 PM      at Object.onReceiveStatus (/opt/render/project/src/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
Feb 1 02:11:02 PM      at /opt/render/project/src/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
Feb 1 02:11:02 PM      at processTicksAndRejections (node:internal/process/task_queues:78:11)
Feb 1 02:11:02 PM  for call at
Feb 1 02:11:02 PM      at ServiceClientImpl.makeUnaryRequest (/opt/render/project/src/node_modules/@grpc/grpc-js/build/src/client.js:163:34)
Feb 1 02:11:02 PM      at ServiceClientImpl.<anonymous> (/opt/render/project/src/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
Feb 1 02:11:02 PM      at /opt/render/project/src/node_modules/@google-cloud/logging/build/src/v2/logging_service_v2_client.js:247:29
Feb 1 02:11:02 PM      at /opt/render/project/src/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
Feb 1 02:11:02 PM      at repeat (/opt/render/project/src/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
Feb 1 02:11:02 PM      at Task._apiCall (/opt/render/project/src/node_modules/google-gax/build/src/normalCalls/retries.js:118:13)
Feb 1 02:11:02 PM      at Task.run (/opt/render/project/src/node_modules/google-gax/build/src/bundlingCalls/task.js:142:35)
Feb 1 02:11:02 PM      at BundleExecutor._runNow (/opt/render/project/src/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:189:14)
Feb 1 02:11:02 PM      at BundleExecutor.schedule (/opt/render/project/src/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:129:18)
Feb 1 02:11:02 PM      at /opt/render/project/src/node_modules/google-gax/build/src/bundlingCalls/bundleApiCaller.js:43:26
```

**Comment by rogi29** [comment] 2023-09-19 16:36
@andreisaikouski
I am not sure if it's still relevant, but I was able solve it by *not* stringifying the JSON and instead passing the JS object as is to the logger. What it did, it truncated the json automatically.
Once it reached the maximum size the logger added a suffix to the logged JSON saying "[message truncated due to size]".
Using `@google-cloud/logging-bunyan@^3.0.2`.
